name: Deploy Azure Environment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Azure Bicep
        run: |
          az group create --name CyberLabRG --location eastus
          az deployment group create --resource-group CyberLabRG --template-file azure-deploy/main.bicep
